name: Deploy Portfolio

on:
  push:
    branches:
      - main  # نام برنچ اصلی خود را چک کنید، اگر master است به master تغییر دهید

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Deploy to Server via SSH
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.SERVER_IP }}
          username: ${{ secrets.SERVER_USER }}
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          script: |
            cd /var/www/portfolio-new
            # اطمینان از هماهنگی کامل با ریپازیتوری گیت‌هاب
            git reset --hard origin/main
            git pull origin main
            
            # ۱. ساخت ایمیج با تزریق متغیر محیطی (Build Argument)
            docker build --build-arg VITE_N8N_WEBHOOK_URL=${{ secrets.VITE_N8N_WEBHOOK_URL }} -t portfolio-app .
            
            # ۲. آزاد کردن پورت 3000 اگر توسط کانتینر دیگری اشغال شده باشد
            CONF_ID=$(docker ps -q --filter "publish=3000")
            if [ ! -z "$CONF_ID" ]; then
              docker stop $CONF_ID
              docker rm $CONF_ID
            fi

            # ۳. حذف کانتینر هم‌نام قبلی برای جلوگیری از تداخل
            docker stop portfolio-container || true
            docker rm portfolio-container || true
            
            # ۴. اجرای کانتینر جدید و متصل کردن پورت 3000 سرور به 80 داکر
            docker run -d --name portfolio-container -p 3000:80 portfolio-app