name: Deploy Portfolio

on:
  push:
    branches:
      - main  # نام برنچ اصلی خود را چک کنید، اگر master است به master تغییر دهید

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Deploy to Server via SSH
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.SERVER_IP }}
          username: ${{ secrets.SERVER_USER }}
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          script: |
            cd /var/www/portfolio-new
            git reset --hard origin/main
            git pull origin main
            
            # ۱. ساخت ایمیج جدید
            docker build -t portfolio-app .
            
            # ۲. پیدا کردن و متوقف کردن هر کانتینری که پورت 3000 را اشغال کرده
            # این دستور هوشمندانه کانتینر مزاحم را پیدا و حذف می‌کند
            CONF_ID=$(docker ps -q --filter "publish=3000")
            if [ ! -z "$CONF_ID" ]; then
              docker stop $CONF_ID
              docker rm $CONF_ID
            fi

            # ۳. اطمینان از حذف کانتینر با نام مشابه برای جلوگیری از تداخل نام
            docker stop portfolio-container || true
            docker rm portfolio-container || true
            
            # ۴. اجرای نهایی کانتینر جدید
            docker run -d --name portfolio-container -p 3000:80 portfolio-app